### ISSUE TITLE
csv file not read

### ISSUE THREAD

**Issue by KevinBattaile** [ww2283/AF-guided-MR#1]
When I try to run with this command:

python main.py --mtz_path staraniso_alldata-unique.mtz --csv_path sequence.csv

I get the following error:

2024-10-22 20:22:06 - ERROR - Error in read_sequences_from_csv: CSV header should start with 'id,sequence'
Traceback (most recent call last):
  File "/nsls2/software/mx/nyx/AF-MR/AF-guided-MR/main.py", line 1115, in <module>
    main()
  File "/nsls2/software/mx/nyx/AF-MR/AF-guided-MR/main.py", line 90, in main
    print(f"Processing {len(sequences)} sequences...")
TypeError: object of type 'NoneType' has no len()

The format of my sequence file is:

trva,PROTEINSEQ

so I think that is correct and am not sure why it isn't being read in. I did the software install as per the instructions, so I think I have everything installed (but maybe not...).

**Comment by ww2283** [comment]
Thank you for reaching out. Please add a header line 'id,sequence' as the first line. So your csv would go like this:
```
id,sequence
trva,PROTEINSEQ
```
This is to comply with the tradition of ColabFold. I will add a check-and-skip for absence of the header line.
I will also push some updates soon which may help with a few certain cases in the benchmark set, but current version should be ok for the vast majority of situations.

**Comment by KevinBattaile** [comment]
Thanks, that fixed it. I also noticed that there can't be any blank lines at the end of the file.
