### ISSUE TITLE
GPU not detected 

### ISSUE THREAD

**Issue by KevinBattaile** [ww2283/AF-guided-MR#2]
When I started the program, It initially dumps to the terminal that it found 2 GPUs and that it is using GPU 0, then after it downloaded the alphafold weights, throws a message that no GPU is detected and it will only be using CPU. 

If I run 'top', I see a colabfold_batch process and if I run 'nvidia-smi' I don't see anything running on either GPU that is associated with a PID that I own. 

The GPUs are nVidia A100.

Is this behaving as expected?

2024-10-23 09:10:22 - INFO - Running ColabFold for sequence trva...
2024-10-23 09:10:22 - INFO - Checking for available GPUs...
2024-10-23 09:10:22 - INFO - Total GPUs: 2
2024-10-23 09:10:22 - INFO - GPU 0: 3627.25 MiB used (4.43% used)
2024-10-23 09:10:22 - INFO - GPU 0 is available
2024-10-23 09:10:22 - INFO - Using GPU 0
2024-10-23 09:10:26,200 Running colabfold 1.5.5 (c21e1768d18e3608e6e6d99c97134317e7e41c75)
Downloading alphafold2_ptm weights to /nsls2/users/kbattaile/.cache/colabfold: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 3.47G/3.47G [00:39<00:00, 93.7MB/s]

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2024-10-23 09:11:06,271 WARNING: no GPU detected, will be using CPU
2024-10-23 09:11:14,671 Found 6 citations for tools or databases
2024-10-23 09:11:14,672 Query 1/1: trva (length 244)
2024-10-23 09:11:16,020 Sleeping for 9s. Reason: PENDING
2024-10-23 09:11:25,884 Sleeping for 5s. Reason: RUNNING
2024-10-23 09:11:31,600 Sleeping for 6s. Reason: RUNNING
2024-10-23 09:11:38,986 Sleeping for 7s. Reason: RUNNING
2024-10-23 09:11:46,699 Sleeping for 8s. Reason: RUNNING

**Comment by ww2283** [comment]
This should relate to the installation of ColabFold part, as this piece of information is generated by ColabFold.
Did you follow the installation part here: https://github.com/ww2283/AF-guided-MR?tab=readme-ov-file#install-colabfold
Have you tried this `pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` in your conda env? Basically jax need to communicate and see your gpu, and if not, it will fall back to use cpu. Which cuda version and nvidia driver version are you using?

**Comment by KevinBattaile** [comment]
Yes, I did that as described. If I repeat it I get an error that cuda11-pip isn't provided. Is this a versioning problem with jax?

(/nsls2/users/kbattaile/conda_envs/automatemr) [kbattaile@mars8 AF]$ pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Requirement already satisfied: jax[cuda11_pip] in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (0.4.35)
WARNING: jax 0.4.35 does not provide the extra 'cuda11-pip'
Requirement already satisfied: jaxlib<=0.4.35,>=0.4.34 in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (from jax[cuda11_pip]) (0.4.35)
Requirement already satisfied: ml-dtypes>=0.4.0 in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (from jax[cuda11_pip]) (0.4.1)
Requirement already satisfied: numpy>=1.24 in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (from jax[cuda11_pip]) (1.26.4)
Requirement already satisfied: opt-einsum in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (from jax[cuda11_pip]) (3.4.0)
Requirement already satisfied: scipy>=1.10 in /nsls2/users/kbattaile/conda_envs/automatemr/lib/python3.10/site-packages (from jax[cuda11_pip]) (1.14.1)

**Comment by ww2283** [comment]
likely a versioning problem with jax. Which cuda version and nvidia driver version are you using?

**Comment by KevinBattaile** [comment]
nvidia-smi reports driver version 560.35.03 and CUDA version 12.6

**Comment by ww2283** [comment]
Ok then please try `pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` because you are using cuda 12 not 11.
